version: "3.9"
services:
  postgres-catalog:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_CATALOG_USER}
      - POSTGRES_PASSWORD=${POSTGRES_CATALOG_PASSWORD}
      - POSTGRES_DB=${POSTGRES_CATALOG_DATABASE}
    env_file:
      - .env.stage
    ports:
      - 5432:5432
    volumes:
      - pgdata-catalog:/var/lib/postgresql/data

  postgres-shopping:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_SHOPPING_USER}
      - POSTGRES_PASSWORD=${POSTGRES_SHOPPING_PASSWORD}
      - POSTGRES_DB=${POSTGRES_SHOPPING_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - pgdata-shopping:/var/lib/postgresql/data
    env_file:
      - .env.stage 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    env_file:
      - .env.stage 
  catalog-svc:
    image: olgatan/catalog-svc:latest
    build: 
      context: .
      dockerfile: src/CatalogService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=${CATALOG_POSTGRES_CONNECTION_STRING} 
    ports:
      - 7001:80
    env_file:
      - .env.stage  
    depends_on:
        - postgres-catalog
        - rabbitmq  
  shoppinglist-svc:
      image: olgatan/shoppinglist-svc:latest
      build: 
        context: .
        dockerfile: src/ShoppingListService/Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Staging
        - ASPNETCORE_URLS=http://+:80
        - RabbitMq__Host=rabbitmq
        - ConnectionStrings__DefaultConnection=${SHOPPING_POSTGRES_CONNECTION_STRING} 
      ports:
        - 7002:80
      env_file:
        - .env.stage
      depends_on:
        - postgres-shopping
        - rabbitmq
  notification-svc:
      image: olgatan/notification-svc:latest
      build: 
        context: .
        dockerfile: src/NotificationService/Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Staging
        - ASPNETCORE_URLS=http://+:80
        - RabbitMq__Host=rabbitmq
      ports:
        - 7003:80
      env_file:
        - .env.stage
      depends_on:
        - rabbitmq
  gateway-svc:
      image: olgatan/gateway-svc:latest
      build: 
        context: .
        dockerfile: src/GatewayService/Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Staging
        - ASPNETCORE_URLS=http://+:80
      env_file:
        - .env.stage
      ports:
        - 7004:80
  web-app:
    image: olgatan/web-app:latest
    build:
      context: .
      dockerfile: frontend/web-app/Dockerfile
    volumes:
      - /var/lib/web/data
    ports:
      - 3000:3000
    env_file:
      - .env # local evn file 
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./devcerts:/etc/nginx/certs:ro
    depends_on:
      - web-app
      - gateway-svc 
    restart: unless-stopped                                            

volumes:
  pgdata-catalog:
  pgdata-shopping: