version: "3.8"
services:
  postgres-catalog:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_CATALOG_USER}
      - POSTGRES_PASSWORD=${POSTGRES_CATALOG_PASSWORD}
      - POSTGRES_DB=${POSTGRES_CATALOG_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - pgdata-catalog:/var/lib/postgresql/data

  postgres-shopping:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_SHOPPING_USER}
      - POSTGRES_PASSWORD=${POSTGRES_SHOPPING_PASSWORD}
      - POSTGRES_DB=${POSTGRES_SHOPPING_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - pgdata-shopping:/var/lib/postgresql/data
  rabbitmq:
      image: rabbitmq:3-management-alpine
      ports: 
      - 5672:5672
      - 15672:15672
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}


volumes:
  pgdata-catalog:
  pgdata-shopping:
