services:
  postgres-catalog:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_CATALOG_USER}
      POSTGRES_PASSWORD: ${POSTGRES_CATALOG_PASSWORD}
      POSTGRES_DB: ${POSTGRES_CATALOG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-catalog:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_CATALOG_USER} -d ${POSTGRES_CATALOG_DATABASE}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-shopping:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_SHOPPING_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SHOPPING_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SHOPPING_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-shopping:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_SHOPPING_USER} -d ${POSTGRES_SHOPPING_DATABASE}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog-svc:
    image: olgatan/catalog-svc:latest
    build:
      context: .
      dockerfile: src/CatalogService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+:80

      ConnectionStrings__DefaultConnection: ${CATALOG_POSTGRES_CONNECTION_STRING}

      RabbitMq__Host: ${RABBIT_MQ_HOST}
      RabbitMq__User: ${RABBIT_MQ_USER}
      RabbitMq__Password: ${RABBIT_MQ_PASSWORD}

      AzureAdB2C__Instance: ${AZURE_AD_B2C_INSTANCE}
      AzureAdB2C__ClientId: ${AZURE_AD_B2C_CLIENT_ID}
      AzureAdB2C__Domain: ${AZURE_AD_B2C_DOMAIN}
      AzureAdB2C__SignUpSignInPolicyId: ${AZURE_AD_B2C_SIGNUP_SIGNIN_POLICY}
      AzureAdB2C__ClientSecret: ${AZURE_AD_B2C_CLIENT_SECRET}
      AzureAdB2C__TenantId: ${AZURE_AD_B2C_TENANT_ID}
      AzureAdB2C__ExtensionId: ${AZURE_AD_B2C_CLIENT_EXTENSION_ID_WITHOUT_DASH}

      ApplicationInsights__ConnectionString: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
    ports:
      - "7001:80"
    env_file:
      - .env.stage
    restart: unless-stopped
    depends_on:
      postgres-catalog:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  shoppinglist-svc:
    image: olgatan/shoppinglist-svc:latest
    build:
      context: .
      dockerfile: src/ShoppingListService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+:80
      RabbitMq__Host: ${RABBIT_MQ_HOST}
      RabbitMq__User: ${RABBIT_MQ_USER}
      RabbitMq__Password: ${RABBIT_MQ_PASSWORD}
      ConnectionStrings__DefaultConnection: ${SHOPPING_POSTGRES_CONNECTION_STRING}

      AzureAdB2C__Instance: ${AZURE_AD_B2C_INSTANCE}
      AzureAdB2C__ClientId: ${AZURE_AD_B2C_CLIENT_ID}
      AzureAdB2C__Domain: ${AZURE_AD_B2C_DOMAIN}
      AzureAdB2C__SignUpSignInPolicyId: ${AZURE_AD_B2C_SIGNUP_SIGNIN_POLICY}
      AzureAdB2C__ClientSecret: ${AZURE_AD_B2C_CLIENT_SECRET}
      AzureAdB2C__TenantId: ${AZURE_AD_B2C_TENANT_ID}
      AzureAdB2C__ExtensionId: ${AZURE_AD_B2C_CLIENT_EXTENSION_ID_WITHOUT_DASH}

      ApplicationInsights__ConnectionString: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
    ports:
      - "7002:80"
    env_file:
      - .env.stage
    restart: unless-stopped
    depends_on:
      postgres-shopping:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-svc:
    image: olgatan/notification-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+:80
      RabbitMq__Host: ${RABBIT_MQ_HOST}
      RabbitMq__User: ${RABBIT_MQ_USER}
      RabbitMq__Password: ${RABBIT_MQ_PASSWORD}

      AzureAdB2C__Instance: ${AZURE_AD_B2C_INSTANCE}
      AzureAdB2C__ClientId: ${AZURE_AD_B2C_CLIENT_ID}
      AzureAdB2C__Domain: ${AZURE_AD_B2C_DOMAIN}
      AzureAdB2C__SignUpSignInPolicyId: ${AZURE_AD_B2C_SIGNUP_SIGNIN_POLICY}
      AzureAdB2C__ClientSecret: ${AZURE_AD_B2C_CLIENT_SECRET}
      AzureAdB2C__TenantId: ${AZURE_AD_B2C_TENANT_ID}
      AzureAdB2C__ExtensionId: ${AZURE_AD_B2C_CLIENT_EXTENSION_ID_WITHOUT_DASH}

      ApplicationInsights__ConnectionString: ${APPLICATIONINSIGHTS_CONNECTION_STRING}

    ports:
      - "7003:80"
    env_file:
      - .env.stage
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

  gateway-svc:
    image: olgatan/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+:80

      AzureAdB2C__Instance: ${AZURE_AD_B2C_INSTANCE}
      AzureAdB2C__ClientId: ${AZURE_AD_B2C_CLIENT_ID}
      AzureAdB2C__Domain: ${AZURE_AD_B2C_DOMAIN}
      AzureAdB2C__SignUpSignInPolicyId: ${AZURE_AD_B2C_SIGNUP_SIGNIN_POLICY}
      AzureAdB2C__ClientSecret: ${AZURE_AD_B2C_CLIENT_SECRET}
      AzureAdB2C__TenantId: ${AZURE_AD_B2C_TENANT_ID}
      AzureAdB2C__ExtensionId: ${AZURE_AD_B2C_CLIENT_EXTENSION_ID_WITHOUT_DASH}

      ApplicationInsights__ConnectionString: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
    env_file:
      - .env.stage
    ports:
      - "7004:80"
    restart: unless-stopped

  web-app:
    image: olgatan/web-app:latest
    build:
      context: .
      dockerfile: frontend/web-app/Dockerfile
      args:
        NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_ID: ${NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_ID}
        NEXT_PUBLIC_AZURE_AD_B2C_TENANT_NAME: ${NEXT_PUBLIC_AZURE_AD_B2C_TENANT_NAME}
        NEXT_PUBLIC_AZURE_AD_B2C_USER_FLOW: ${NEXT_PUBLIC_AZURE_AD_B2C_USER_FLOW}
        NEXT_PUBLIC_AZURE_AD_B2C_PROFILE_EDIT_FLOW: ${NEXT_PUBLIC_AZURE_AD_B2C_PROFILE_EDIT_FLOW}
        NEXT_PUBLIC_AZURE_AD_B2C_CATALOG_WRITE_SCOPE: ${NEXT_PUBLIC_AZURE_AD_B2C_CATALOG_WRITE_SCOPE}
        NEXT_PUBLIC_AZURE_AD_B2C_CATALOG_READ_SCOPE: ${NEXT_PUBLIC_AZURE_AD_B2C_CATALOG_READ_SCOPE}
        NEXT_PUBLIC_AZURE_AD_B2C_SHOPLIST_READ_SCOPE: ${NEXT_PUBLIC_AZURE_AD_B2C_SHOPLIST_READ_SCOPE}
        NEXT_PUBLIC_AZURE_AD_B2C_SHOPLIST_WRITE_SCOPE: ${NEXT_PUBLIC_AZURE_AD_B2C_SHOPLIST_WRITE_SCOPE}

        NEXT_PUBLIC_AZURE_AD_B2C_REDIRECT_URI: ${NEXT_PUBLIC_AZURE_AD_B2C_REDIRECT_URI}
        NEXT_PUBLIC_AZURE_AD_B2C_EDIT_PROFILE_REDIRECT_URI: ${NEXT_PUBLIC_AZURE_AD_B2C_EDIT_PROFILE_REDIRECT_URI}

        NEXT_PUBLIC_GATEWAY_URL: ${NEXT_PUBLIC_GATEWAY_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env.stage
    restart: unless-stopped

volumes:
  pgdata-catalog:
  pgdata-shopping:
